// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDW2XNMLF2R_MHddGY9ZyrHRxywwmylVvg',
    appId: '1:21334838205:web:6eef0275e8f26f0caa20d4',
    messagingSenderId: '21334838205',
    projectId: 'horoscope-for-all',
    authDomain: 'horoscope-for-all.firebaseapp.com',
    storageBucket: 'horoscope-for-all.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    // apiKey: 'AIzaSyD6ZXUR7KJSxJPAKhDMLdCfxApE8PQPoZo',
    apiKey: 'AIzaSyDTMJSAqUfD-9BY6Icc4iwu_fnew-qR46c',
    // appId: '1:21334838205:android:9d58837a435c7c70aa20d4',
    appId: '1:746332400549:android:83fccfffeb467cac1a164c',
    // messagingSenderId: '21334838205',
       messagingSenderId: '746332400549',
    // projectId: 'horoscope-for-all',
    projectId: 'invent-dev',
    // storageBucket: 'horoscope-for-all.appspot.com',
    storageBucket: 'invent-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdHcKJkp3p1XXnlJnjQShfancuBN-FwgY',
    appId: '1:21334838205:ios:601b78bb3c5cc46faa20d4',
    messagingSenderId: '21334838205',
    projectId: 'horoscope-for-all',
    storageBucket: 'horoscope-for-all.appspot.com',
    iosBundleId: 'com.neo321654.adminHoroscope',
  );
}
